sh scripts/train_model_1.sh
sh scripts/train_model_2.sh
sh scripts/train_model_3.sh
sh scripts/train_model_4.sh
sh scripts/train_model_5.sh
sh scripts/train_model_6.sh
sh scripts/train_model_7.sh
sh scripts/train_model_8.sh
sh scripts/train_model_9.sh
sh scripts/train_model_10.sh
sh scripts/train_model_11.sh